import React, { createContext, useState } from 'react'


export let store = createContext();


const ContextApi = (props) => {
    let [data, setData] = useState([
      {id:1, icon:"Home", cat:"homebanner", img:"https://images.pexels.com/photos/1233414/pexels-photo-1233414.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", heading:"The Beauty of Nature " ,command:" The beauty of nature is all around us, from the towering mountains to the crashing waves of the ocean. We can find beauty in the smallest of things, like a single flower or a dewdrop on a leafasedsr.",extrecom:" Nature is a source of inspiration for artists, poets, and musicians.It can help us to relax and de-stress, and it can also teach us about the interconnectedness of all life.We must protect nature for future generations to enjoy.Title: The Power of NatureNature is a powerful force that can create and destroy.It can give us life-giving water and food, but it can also unleashdevastating storms and earthquakes.Nature is a reminder of our own smallness and fragility.It can teach us humility and respect for the natural world.We must learn to live in harmony with nature, or we will suffer the consequences."},
      {id:2,  icon:"Home",cat:"homebanner1", img:"https://th.bing.com/th?id=OIP.P1xzFzeXR3-Vy7rQJoEOPAHaLE&w=204&h=305&c=8&rs=1&qlt=90&o=6&dpr=1.6&pid=3.1&rm=2", heading:"The Power of Nature " ,extrecom:"Nature is the creation of natural material and physical world on earth independent of the human activities. The beauty and richness of nature is diverse and massive. Nature provides us with several delicacies to enjoy and is our life support system. Our basic needs like food, shelter, water and air are all the gifts from nature. Humans have a strong connection and interrelation with nature. Escaping away in the nature heals the mind and body and soothes our soul. Irrespective of what nature provides us it is also our moral and social responsibility to nurture nature. ",command:" ““We are all dreaming of some magical rose garden over the horizon instead of enjoying the roses blooming outside our windows today.” – Dale Carnegie"},
      {id:3, icon:"Home",cat:"homebanner2", img:"https://th.bing.com/th?id=OIP.BSGCzSyrG9GYL7Hus1Rm_gHaEf&w=320&h=194&c=8&rs=1&qlt=90&o=6&dpr=1.6&pid=3.1&rm=2", heading:"ROSES " ,extrecom:"You will find below a number of short and long paragraphs on Nature. We hope these Nature paragraphs will help students in completing their school assignments. These will also help children to write and read out paragraphs with simple words and small sentences. Students can select any paragraph on Nature according to their particular requirement. ",command:" ““We are all dreaming of some magical rose garden over the horizon instead of enjoying the roses blooming outside our windows today.” – Dale Carnegie"}, 
      {id:4, icon:"Home",cat:"the latest", img:"https://th.bing.com/th/id/R.91e206fa02d81f85dd4e42ef005a88d9?rik=5MxgANLhpAlBJw&riu=http%3a%2f%2fthewowstyle.com%2fwp-content%2fuploads%2f2015%2f07%2fautunm-desktop-natural-hd-wallpapers.jpg&ehk=j7yVlSgUBySdpPIKhx0ovaCIvpI2u%2f%2bw3lfHET9HT4w%3d&risl=1&pid=ImgRaw&r=0", heading:" Study nature, love nature, stay close ." ,extrecom:" The serenity of nature calms our hearts. The stillness and movement in nature both have a hypnotizing effect. The unfolding creativity of nature is an art. It is alluring to experience solitude with nature. The practice of devoting ourselves to the bliss of nature is soothing and reviving. Everyone loves to escape away in the mysteries of nature.",command:" In nature, nothing is perfect and everything is perfect. Trees can be contorted, bent in weird ways, and they're still beautiful. –Alice Walker"},
      {id:5, icon:"Home",cat:"the latest", img:"https://tse3.mm.bing.net/th/id/OIP.S1dPiODc5rCcWObk4DThygHaEo?pid=ImgDet&rs=1", heading:" Live in each season as it passes" ,extrecom:"Nature refers to the physical world and all forms of life species on earth in general. Our natural ecosystem is the community of biotic and abiotic components. The biotic components are the living organisms that also include humans. Abiotic components are the non-living components such as air, water, minerals and soil. The biotic and abiotic components are interrelated and interact with each other through energy flow. ",command:"Forget not that the earth delights to feel your bare feet and the winds long to play with your hair. —Khalil Gibran"},
      {id:6, icon:"Home", cat:"the latest", img:"https://tse4.mm.bing.net/th/id/OIP.UYV_bihup-y039M8_Dk0KQHaFP?pid=ImgDet&rs=1", heading:"Preserve and cherish the pale blue",extrecom:"Natural ecosystem also includes the interrelation between diverse organisms and their environment. Natural ecosystem obtains energy primarily from sun through photosynthesis. Through the process of photosynthesis plants obtain energy from sunlight and absorb carbon dioxide from atmosphere. Plants combine carbon dioxide and water to produce oxygen and carbohydrates. The energy obtained by plants is consumed by animals. Animals also play important role in nutrient cycle and flow of energy. They influence plants and other micro-organisms in the ecosystem. Thus the energy enters ecosystem through the process of photosynthesis and is transferred to the living organisms. Thus, natural ecosystem supports life on earth. ",command: "Heaven is under our feet as well as What Does Natural Content Do? In its shrewdest terms, “natural”  over our heads. —Henry David Thoreau"},
      {id:7, icon:"Home", cat:"latestarticles", img:"https://wallpapercave.com/wp/mXXyO8i.jpg", heading:"Henry David Thoreau",extrecom:"However where ever we travel we should travel in a responsible manner and should not damage the environment and avoid throwing away waste and trash on the roads and public places to maintain the cleanliness.drink the drink, taste the fruit, and resign yourself to the influence of the earth. —Henry David Thoreau We should protect and care for the nature and natural surroundings as we all want to preserve the beauty and richness of nature for future generations.",command:"Live in each season as it passes; breathe the air"},
      {id:8, icon:"Home", cat:"latestarticles", img:"https://tse4.mm.bing.net/th/id/OIP.lhiRRDyaTheR4r-I8xAX1QHaHa?pid=ImgDet&w=500&h=500&rs=1", heading:"nature to be soothed",extrecom:"Nature is beautiful not because it meets our several needs but because of the way all these natural forms render the feeling of bliss and help us connect with our true selves. The experience of this natural beauty diverse and intense is the heart of nature. Every part of nature is beautiful and unique in itself. Every single moment God is painting the new stroke of beauty in nature. Nature includes the natural and physical world including animals, birds, landscapes and other features and creations that exist on earth independent human creations.  and to have my senses put in order. —John Burroughs",command:" I go to nature to be soothed and healed"},
      {id:9, icon:"Home",cat:"latestarticles", img:"https://tse3.mm.bing.net/th/id/OIP.0rAyTjK7IuDQZhja0oOThgHaEo?pid=ImgDet&rs=1", heading:"What Does Natural Content",extrecom:"Nature’s beauty is revealed everywhere around us all the time. Morning dew on the velvet green grass, the flowers falling from the tree in the backyard, the sparrow building its nest on the tree, butterflies here and there – everything is nature’s beauty. Nature is alive, expressive and fruitful., “natural” content is written to inform a human person, not to satisfy the requirements of an antiquated search bot.  ",command:"  What Does Natural Content Do? In its shrewdest terms" },
      {id:10, icon:"Home", cat:"latestarticles", img:"https://fastly.4sqi.net/img/general/600x600/8771015_fFJaxrUstL3pe4-4LRoORITPNBIB_aMZ-pLYZo4SQr4.jpg", heading:"For most of history, ",extrecom:" Nature is an art performing and evolving all the time so beautifully. The connection with nature has a calming effect that heals us. The freshness and purity of nature rejuvenates us. When we experience solitude in nature we feel real peace and tranquility of nature. One needs to lose deep in to the nature to feel the heart of nature. The beauty and richness of nature is beyond words and beyond imagination.in this century he is beginning to realize that, in order to survive, he must protect it. —Jacques-Yves Cousteau",command:"For most of history, man has had to fight nature to survive; " },
      {id:11, icon:"Home", cat:"latestarticlesimg", img:"https://tse1.mm.bing.net/th/id/OIP.3MxqaJv2Z5QsG7wIXzizjAHaEo?pid=ImgDet&rs=1", heading:"For most of history",extrecom:"The most interesting fact about nature is the diversity of nature. It is the true beauty of nature. The diversity in nature has important role to play in the lifecycle on earth. The variety of life species on the earth is known as biodiversity of nature. It refers to the diversity of plants, animals, organisms, birds, bees etc. It also includes small microorganisms, fungi, algae, bacteria and many other insects and tiny creatures. It encompasses the diverse nature of ecosystem such as forests, desserts, mountains, rainforests and oceans. All are these are a part of nature. ",command:" For most of history, man has had to fight nature to survive; in this century he is beginning to realize that, in order to survive, he must protect it. —Jacques-Yves Cousteau" },
      {id:12, icon:"Home", cat:"newtophome",num:"1",  img:"https://images.pexels.com/photos/16128579/pexels-photo-16128579/free-photo-of-landscape-of-a-river-and-mountains.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", heading:"Wind" ,extrecom:"Nature refers to the natural resources and natural surroundings. The life species in nature are interrelated and create balance in nature. They form a natural food chain through which energy is passed to all the species. The series of organisms in which each organism feeds on the one below it in the sequence is called the food chain in natural ecosystem. Food chain includes several plants, organisms, animals and other living species. This natural food chain is the source of energy for the forest species. The energy is passed from one creature to the other which helps them grow and survive. ",command:" There’s a whole world out there, right outside your window. You’d be a fool to miss it. —Charlotte Eriksson "},
      // {id:13, icon:"Home", cat:"Hometop", img:"https://wallpapertag.com/wallpaper/full/d/3/c/968676-hi-res-background-images-2651x1813-retina.jpg", heading:"pale blue" ,extrecom:"Nature comprises of the connection between the life species, their habitat, their activities, living conditions and survival process. Biodiversity is measured higher in the tropical and floristic regions. The best studied species are mostly the large mammals. The diversity in nature cannot be measured in figures but all the living species large or tiny have an important role to play in nature. Biodiversity is responsible for balanced ecosystem. The spread of biodiversity varies across the globe depending on the soil, temperature, rainfall, altitude and geography. ",command:"Preserve and cherish the pale blue dot, the only home we've ever known. —Carl Sagan"},
      {id:14, icon:"Home", cat:"Hometop",num:"2", img:"https://th.bing.com/th/id/R.01f64e437e2ffe2031194501d51d39c1?rik=LQEJlfeBEydW4Q&riu=http%3a%2f%2fthewowstyle.com%2fwp-content%2fuploads%2f2015%2f07%2fnatural-abundance.jpg&ehk=ok06Oig2qElKJ1PEHhgjZKY1GyZmKLoWSYsmoONoYuM%3d&risl=1&pid=ImgRaw&r=0", heading:"When we think of the beauty of nature",extrecom:"Biodiversity is valuable to humans. Biodiversity forms the base of infinite economic services that contribute to overall well-being of humans. Growth in population and economic development has led to inefficient use of biodiversity. Biodiversity has threats from human activities. Exploiting biodiversity can cause loss of species important for natural balance. Preservation and sustainable use of biodiversity is vital. Biodiversity is a gift from nature and we all should shield and protect it from further harm. ",command:"Study nature, love nature, stay close to nature. It will never fail you. —Frank Lloyd Wright"},
      {id:14, icon:"Home", cat:"Hometop",num:"3",  img:"https://wallpapercave.com/wp/mXXyO8i.jpg", heading:"When we observe and feel the beauty",extrecom:"When we observe and feel the beauty of nature it has such a tranquil and soothing effect on our mind, body and soul. It has a lasting effect on our senses and gives an amazing feeling of refreshment and delight. When we think of the beauty of nature we immediately think of the scenic and visual beauty of nature, like the soaring mountains, tranquil rivers, greeneries of trees, colors of rainbow, butterflies and birds, and the blossoming flowers. Everything about nature gives us the feeling of pleasure. ",command:"Study nature, love nature, stay close to nature. It will never fail you. —Frank Lloyd Wright"},
    
      {id:15, icon:"Home", cat:"Hometop",num:"4",  img:"https://i.pinimg.com/736x/f3/41/e9/f341e94851147b91d314bcfc4765c72e.jpg", heading:"Nature refers to the natural resources",extrecom:"Nature refers to the natural resources, plants, animals and other forms of living and non living things that exist naturally in the universe. One very important part of nature is the wildlife. Nature includes rich and diverse wildlife. Wildlife mostly refers to the undomesticated animal species, but also comprises other species like plant, fungi and other organisms that exist and penetrate independent of human intrusion. as if it had nothing else in the universe to do. —Galileo Galilei  ",command:"The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes"},
      {id:16, icon:"Home", cat:"LateststoryHome", img:"All my life through, the new sights of Nature made me rejoice like a child", heading:" The Latest Story" ,extrecom:"For example in forest deer feeds on the grass and green plants and the tiger feeds on the deer. Plants get their energy form sunlight and nutrients from soil. Deer is herbivores animal. Herbivores animals depend on plants for energy and are vegetarians. Tiger is carnivorous animal. Carnivorous animals eat herbivores and sometimes other carnivorous for energy. So there is a whole chain that includes plants, herbivores, carnivorous and plants consume energy from sunlight. And there are lots of animals that eat plants and meat both. These are called omnivorous animals. For instance, black beer is an omnivorous animal. Some omnivorous also eat dead animals and those are called scavengers. Thus, the chain goes on. ",command:"Use what talents you possess: the woods would be very silent if no birds sang there except those that sang best"},
      {id:17, icon:"Home", cat:"LateststoryHome", img:"Let the rain kiss you. Let the rain beat upon your head with silver liquid drops. ", heading:"  The Latest Story" ,extrecom:"The beauty of nature is unimaginable. Everyone is attracted by nature’s beauty and diversity. There are several natural attractions in different parts of the world. People have always appreciated and valued the beauty of nature. They travel far and wide to enjoy this scenic natural beauty. ",command:"The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do"},
      {id:18, icon:"Home", cat:"LateststoryHome", img:"Study nature, love nature, stay close to nature. It will never fail you. —Frank Lloyd Wright", heading:" The Latest Story " ,extrecom:" Natural tourism refers to the tourism to areas of natural attractions. Natural attractions include mountains, rivers, beaches, wood lands etc. that also include diverse life forms of plants, birds and animals. There are several natural attractions shaped by the unique natural features of surrounding environment. People escape away to these destinations to enjoy nature, relax and perform adventurous activities.",command:"Sunshine is delicious, rain is refreshing, wind braces us up, snow is exhilarating; there is really no such thing as bad weather, only different kinds of good weather. "},
      
      
      
      
      {id:19,num:"1",  icon:"Bollywood",cat:"BollywoodTopposthigh", img:"https://th.bing.com/th?id=OSK.HERO3B0gX5xXz8Wam7-1JAETOBZuYImTsCvCa4OsnIHKA14&w=280&h=185&c=15&rs=2&o=6&oif=webp&dpr=1.6&pid=SANGAM ", heading:"Shah Rukh Khan" ,extrecom:"Khan's first starring role was in Lekh Tandon's television series Dil Dariya, which began shooting in 1988, but production delays led to the Raj Kumar Kapoor directed 1989 series Fauji becoming his television debut instead.[37] In the series, which depicted a realistic look at the training of army cadets, he played the leading role of Abhimanyu Rai.[38][39] This led to further appearances in Aziz Mirza's television series Circus (1989–90) and Mani Kaul's miniseries Idiot (1992).[40] Khan also played minor parts in the serials Umeed (1989) and Wagle Ki Duniya (1988–90),[40] and in the English-language television film In Which Annie Gives It Those Ones (1989).[41] His appearances in these serials led critics to compare his look and acting style with those of the film actor Dilip Kumar,[42] but Khan was not interested in film acting at the time, thinking that he was not good enough.[ ",command:"Shah Rukh Khan also known by the initialism SRK, is an Indian actor and film producer. "},
      // {id:20,icon:"Bollywood", cat:"bollywoodtop", img:"https://i2.cinestaan.com/image-bank/1500-1500/58001-59000/58937.jpg", heading:"Ranbir Kapoor",extrecom:"In a collaboration with director Anurag Basu, Kapoor formed a production company named Picture Shuru Productions, whose first release was the musical comedy-mystery film Jagga Jasoos (2017), which tells the story of a gifted teenager's search for his missing stepfather.[87] Production on the project was plagued with difficulties—principal photography began in 2014, but the release date was pushed back several times owing to changes in the script, multiple reshoots, and rumours of animosity between Kapoor and co-star Katrina Kaif (the couple had broken-up before they finished filming).[88][89] Anna M. M. Vetticad of Firstpost considered the film to be a laudable experiment that zigzags off course, and while praising Kapoor's dedication to his part, criticised the decision to cast him as a teenage schoolboy.[90] It did not perform well commercially which led Kapoor to regret his venture into production. ", command :"Ranbir Kapoor is an Indian actor known for his work in Hindi-language films. "},
      // {id:21,icon:"Bollywood", cat:"bollywoodtop", img:"https://tse3.mm.bing.net/th/id/OIP.rb2mVsh3PcnBsdAECk7CewHaFn?pid=ImgDet&rs=1", heading:"Deepika Padukone ",extrecom:"Padukone was born on 5 January 1986 in Copenhagen, Denmark, to Konkani-speaking parents.[1][2][3] Her father, Prakash Padukone, is a former professional badminton player and her mother, Ujjala, is a travel agent.[4] Her younger sister, Anisha, is a golfer.[5] Her paternal grandfather, Ramesh, was a secretary of the Mysore Badminton Association.[6] The family relocated to Bangalore, India when Padukone was a year old.[7] She was educated at Bangalore's Sophia High School and completed her pre-university education at Mount Carmel College.[8] She subsequently enrolled at the Indira Gandhi National Open University for a Bachelor of Arts degree in sociology, but dropped out due to scheduling conflicts with her modelling career ",command:"Deepika Padukone (pronounced [d̪iːpɪka pəɖʊkoːɳeː] or [paːɖʊkoːɳ]; born 5 January 1986) is an Indian actress who works predominantly in Hindi films. "},
      // {id:22,icon:"Bollywood", cat:"bollywoodtop", img:"https://lh6.googleusercontent.com/-Ykl89bUroII/AAAAAAAAAAI/AAAAAAAAABw/cL_fU5wjboM/photo.jpg", heading:"Alia Bhatt",extrecom:"Bhatt had her first leading role in 2012 with Karan Johar's teen film Student of the Year, alongside newcomers Sidharth Malhotra and Varun Dhawan.[25] She auditioned alongside 500 girls and was cast after losing 16 kg (35 lb).[21] She played a sophisticated teenage girl involved in a love triangle. Anupama Chopra of Hindustan Times mentioned similarities between her character and Kareena Kapoor's role in Johar's Kabhi Khushi Kabhie Gham... (2001), but noted that her performance was without the killer attitude.[26] Lisa Tsering of The Hollywood Reporter dismissed her as a washout. Not only is she inelegant in the dance numbers, but her expressions are limited; and the digital retouching of her face throughout the film is a distraction.[27] The film grossed ₹960 million (US$12 million) at the box office, becoming a commercial success.[28] ",command:"Alia Bhatt was born on 15 March 1993[4][5] into the Bhatt family to Indian film director Mahesh Bhatt and actress Soni Razdan. Her father is of Gujarati descent[6][7] and her mother is of Kashmiri Pandit and British German ancestry."},
      {id:23,num:"2", icon:"Bollywood", cat:"bollywoodtop", img:"https://tse1.mm.bing.net/th/id/OIP.BanAOIQZeNOIQvBpLSekNQHaFM?pid=ImgDet&w=570&h=400&rs=1", heading:"Priyanka Chopra" ,extrecom:"Chopra ventured into music by releasing three singles and into writing with her memoir Unfinished (2021), which reached The New York Times Best Seller list. Her other ventures include tech investments, a haircare brand, a restaurant, and a homeware line. She promotes social causes such as environment and women's rights and is vocal about gender equality, the gender pay gap, and feminism. She has worked with UNICEF since 2006 and was appointed as the national and global UNICEF Goodwill Ambassador for child rights in 2010 and 2016, respectively. Her namesake foundation for health and education works towards providing support to underprivileged Indian children. Despite maintaining privacy, Chopra's off-screen life, including her marriage to American singer and actor Nick Jonas, is the subject of substantial media coverage. The couple has one daughter. On Instagram, Chopra is the most-followed Indian actor. ",command:"Priyanka Chopra Jonas (born  1982) is an Indian actress and producer. The winner of the Miss World 2000"},
      {id:24,num:"3", icon:"Bollywood", cat:"bollywoodtop", img:"  https://th.bing.com/th/id/R.fda281d546d6f6630a50d523d93857ad?rik=ndJZB6EuFiNwBg&riu=http%3a%2f%2f3.bp.blogspot.com%2f_rRd950htNgQ%2fTM52vSi03JI%2fAAAAAAAAAGc%2fTU8AFRAMz5g%2fs1600%2f6.jpg&ehk=%2bfntlFl%2bucXRvvrJTST4XIJxfGw6LOiJr2Payqu2aE8%3d&risl=&pid=ImgRaw&r=0", heading:"Asin",extrecom:" Asin was born on 26 October 1985[10][11][12] at Kochi in the state Kerala in a Malayali Syro-Malabar Catholic family.[13] Her father Joseph Thottumkal is an Ex-CBI officer and later managed several businesses. Her mother Seline Thottumkal, who moved from Kochi to Chennai and then to Mumbai to live with her daughter, is a surgeon. According to custom, Asin was to be named Mary, after her paternal grandmother. Asin's father however, named her Asin as the name had a beautiful meaning.[14] Asin has quoted that her name means pure or without blemish.[15] She states that the 'A' in her name is from Sanskrit",command:"Asin Thottumkal (born 26 October 1985), known mononymously as Asin, is a Indian former actress who appeared"},
      {id:25,num:"4",  icon:"Bollywood",cat:"bollywoodtop", img:"https://tse2.mm.bing.net/th/id/OIP.blyVbc89fmGU1R-jPuJc6QHaEf?pid=ImgDet&rs=1", heading:"Ranveer Singh Bhavnani ",extrecom:"After completing his studies and returning to Mumbai in 2007, Singh worked for a few years in advertising as a copywriter, with agencies like O&M and J. Walter Thompson.[8][15] He also worked as an assistant director but left it to pursue acting. He then decided to send his portfolio to directors.[15] He would go for all kinds of auditions, but did not get any good opportunities, while only getting calls for minor roles ",command:"Ranveer Singh Bhavnani (pronounced [rəɳˈʋiːr sɪŋ]; born 6 July 1985) is an Indian actor who works in Hindi films."},
      // {id:26,icon:"Bollywood", cat:"bollywood", img:"https://www.tamilstar.com/wp-content/uploads/2020/04/dc-Cover-g479bq7ek1prgbd4lp5olpil20-20161227230409.Medi_.jpeg",  heading:"Thalapathi vijay",extrecom:" Following the action-romance flick Thirumalai in 2003, Ghilli, a film directed by S. Dharani and produced by A. M. Rathnam, was released. It co-starred Trisha and Prakash Raj with Vijay as the lead.[39] Ghilli was the first Tamil film of all time to gross over ₹500 million, or ₹50 crore, in the domestic box office.[40] The film grossed nearly $500,000 in the Malaysian market.[41] Ghilli also broke the record for the most people seeing a movie in the first week of its release, previously held by M. G. Ramachandran's Adimai Penn (1969).[41] Ghilli received favourable reviews.[42] The Hindu stated that Vijay, the hero whom the masses today identify with, and Prakash Raj, the inimitable villain in tow, this flick",command:"Joseph Vijay Chandrasekhar (born 22 June 1974 ), known professionally as Vijay, is an Indian actor and singer who works predominantly in Tamil cinema. "},
      // {id:27,icon:"Bollywood", cat:"bollywood", img:"https://www.filmfare.com/awards/filmfare-awards-south-2017/images/nominations/vikram.jpg",  heading:"Vikaram Actor",extrecom:" Vikram was born as Kennedy John Victor on 17 April 1966 to a Christian father and a Hindu mother.[9] His father, John Victor (alias Vinod Raj) was a native of Paramakudi and ran away from home to start a career in films, but worked only in minor roles. Vikram's mother, Rajeshwari, was a government officer who reached the rank of sub-collector. Rajeshwari was born in a Hindu family with film connections. Her brother, Thiagarajan, is an established director-actor in the Tamil film industry; he is the father of actor Prashanth, making him Vikram's first cousin (although the two have never openly acknowledged this relationship).[10] Vikram has two siblings, both younger to him. His brother, Arvind, appeared in the low-budget Tamil film, Eppo Kalyanam (2022).",command:"Kennedy John Victor (born 17 April 1966), better known by his stage name Vikram, is an Indian actor who predominantly works in Tamil cinema."},
      {id:28,icon:"Bollywood", cat:"bollywood", img:"https://th.bing.com/th/id/R.0f8cb57b27be9de7156e5b323d3cac83?rik=fdjAc%2fUPX1WGhQ&riu=http%3a%2f%2f2.bp.blogspot.com%2f-BQlBLsBzAJw%2fU-eET2EzrDI%2fAAAAAAAAZVI%2fYMyBRvmbsV0%2fs1600%2f10394003_845193702180620_5183650803751353453_n.jpg&ehk=0oagnUiaJ26NjGNid3tskmivJAO1oDEiMjhcq8mH0Wc%3d&risl=&pid=ImgRaw&r=0",  heading:"Suriya",extrecom:"Suriya was born as Saravanan on 23 July 1975 in Madras (now Chennai), Tamil Nadu, to actor Sivakumar and his wife Lakshmi. He attended Padma Seshadri Bala Bhavan School[12] and St. Bede's Anglo Indian Higher Secondary School in Chennai,[13] and obtained his under graduate degree B.Com from Loyola College, Chennai.[14] Suriya has two younger siblings, a brother Karthi and a sister Brindha. ",command:"Saravanan Sivakumar, known by his stage name Suriya, is an Indian actor and film producer. He primarily works in Tamil cinema where he is one of the highest paid actors"},
      {id:29,icon:"Bollywood", cat:"bollywood", img:"https://tse1.mm.bing.net/th/id/OIP.3ZltInn6LAjaUCLuHS8QcgHaLH?pid=ImgDet&rs=1",  heading:"Karthi" ,extrecom:"Karthi was born Karthik Sivakumar on 25 May 1977 in Madras (now Chennai), Tamil Nadu, India. He completed his elementary and secondary school education at Padma Seshadri Bala Bhavan and St. Bede's Anglo Indian Higher Secondary School, Chennai.[6] He gained a bachelor's degree in mechanical engineering from Crescent Engineering College, Chennai.[7] After graduation, he worked as an Engineering consultant in Chennai and considered higher studies abroad. ",command:"Karthik Sivakumar (born 25 May 1977), known as Karthi, is an Indian actor who works predominantly in Tamil cinema. "},
      {id:30, icon:"Bollywood",cat:"bollywood", img:"https://tse2.mm.bing.net/th/id/OIP.L9LSR1RnzLLWKgQ4B5PbOwHaK_?pid=ImgDet&rs=1",  heading:"Sivakarthikeyan " ,extrecom:"In 2013, he appeared in three films. In his first release of the year, Kedi Billa Killadi Ranga, a dual hero coming-of-age comedy, Sivakarthikeyan partnered once again with Pandiraj and shot for the film in his hometown of Tiruchirappalli alongside Vimal.[15] The film opened to positive reviews with critics.[16][17] The film became a surprise success at the box office and ended up being a profitable venture for producers and distributors.[18] His next success was through Dhanush's debut production venture Ethir Neechal, written and directed by R. S. Durai Senthilkumar, a former assistant of film director, Vetrimaaran. It is a story about a young man having talent as a runner, who strives to make an identity for himself. His third release in 2013, director Ponram's comedy Varuthapadatha Valibar Sangam, saw him portray a carefree rural youth where he paired up with another newcomer Sri Divya. ",command:"Sivakarthikeyan is an Indian actor, lyricist, and television presenter predominantly working in the Tamil film industry12. He was born on February 17, 1985."},
      {id:31, icon:"Bollywood",cat:"bollywood", img:"https://tse1.mm.bing.net/th/id/OIP.emg2hmTKkY0r1rI2Z4nixwHaIy?pid=ImgDet&rs=1",  heading:"Ajith Kumar" ,extrecom:" Ajith became a racing driver, competing in circuits around India in places such as Mumbai, Chennai and Delhi. He is one among very few Indians to race in the International arena and in Formula championships. He has also been abroad for various races, including Germany and Malaysia. He drove in the 2003 Formula Asia BMW Championships.[8] He raced in the 2010 Formula 2 Championship along with two other Indians, Armaan Ebrahim and Parthiva Sureshwaren.[9]",command:"Ajith Kumar is an Indian actor who works predominantly in Tamil cinema. To date, he has starred in over 61 films, and his awards include four Vijay Awards, three Cinema"}, 
      {id:32,icon:"Bollywood", cat:"bollywood", img:"https://th.bing.com/th/id/R.4a330094ede8b209790af045b9b84dc4?rik=6vinDk1NpgDPNQ&riu=http%3a%2f%2f3.bp.blogspot.com%2f-FqCefXkDeMQ%2fTzueaHuAHAI%2fAAAAAAAACoU%2fv2QZoHUHjX4%2fs1600%2fTrisha%2bLatest%2bHot%2bPhotos%2b3.jpg&ehk=5E59koRP9pj6HxOAofezK5u5MbrckP%2b8C9RU9Ab9rLw%3d&risl=&pid=ImgRaw&r=0",  heading:"Trisha Krishnan " ,extrecom:"Later in 2004, she acted as the female lead opposite Vijay in the action comedy film Ghilli. She played the character of Dhanalakshmi, a helpless girl who is protected from a thug by a Kabaddi player. However, most critics agreed that her performance in this film was overshadowed by Vijay and Prakash Raj.[43][44] The film eventually emerged as the highest-grossing Tamil film of the year, celebrating a 175-day run,[45][46] and was Trisha's biggest commercial success at the time. She next appeared in a small role in Mani Ratnam's political drama Aayutha Ezhuthu (2004), starring as part of an ensemble cast that included Siddharth, Madhavan and Surya. The film, despite favourable reviews, performed poorly at the box office, and she was once again outshone by the three male lead actors. ",command:"Trisha Krishnan (born 4 May 1983) is an Indian model and actress who works predominantly in Tamil and Telugu films."},
      {id:33,icon:"Bollywood", cat:"bollywood", img:"https://tse3.mm.bing.net/th/id/OIP.IbpySuAOWirLyfD4d0xQ5wHaKX?pid=ImgDet&rs=1",  heading:"Nayanthara " ,extrecom:"She began her acting career in 2003 with the Malayalam film Manassinakkare.While studying at college, Nayanthara worked part-time as a model.[23][24] She was spotted by director Sathyan Anthikkad, who had seen some of her modelling assignments and approached her to play a pivotal role in his film Manassinakkare (2003).[23] Although she turned down the offer initially, as she was not interested in films, she gave in eventually and agreed to do just that one film.[23] Manassinakkare went on to become a big financial success and she continued to receive acting offers. Both her releases in 2004, Natturajavu by Shaji Kailas, and Fazil's psychological thriller Vismayathumbathu, saw her co-starring alongside Mohanlal; while she played the protagonist's adopted sister in the former, she portrayed a ghost in the latter.[25] Her performance in Vismayathumbathu, in particular, was lauded, with critics claiming that she had stolen the thunder with her author-backed role" ,command:"Diana Mariam Kurian (born 18 November 1984), known professionally as Nayanthara, is an Indian actress and film producer who predominantly appears in Tamil, Malayalam and Telugu films"},
      {id:34,icon:"Bollywood", cat:"bollywoodbott", img:"https://tse2.mm.bing.net/th/id/OIP.L9LSR1RnzLLWKgQ4B5PbOwHaK_?pid=ImgDet&rs=1",  heading:"Sivakarthikeyan " ,extrecom:"In 2013, he appeared in three films. In his first release of the year, Kedi Billa Killadi Ranga, a dual hero coming-of-age comedy, Sivakarthikeyan partnered once again with Pandiraj and shot for the film in his hometown of Tiruchirappalli alongside Vimal.[15] The film opened to positive reviews with critics.[16][17] The film became a surprise success at the box office and ended up being a profitable venture for producers and distributors.[18] His next success was through Dhanush's debut production venture Ethir Neechal, written and directed by R. S. Durai Senthilkumar, a former assistant of film director, Vetrimaaran. It is a story about a young man having talent as a runner, who strives to make an identity for himself. His third release in 2013, director Ponram's comedy Varuthapadatha Valibar Sangam, saw him portray a carefree rural youth where he paired up with another newcomer Sri Divya. ",command:"Sivakarthikeyan is an Indian actor, lyricist, and television presenter predominantly working in the Tamil film industry12. He was born on February 17, 1985."},
      
      {id:35,icon:"Bollywood", cat:"bollywoodbott", img:"https://tse1.mm.bing.net/th/id/OIP.emg2hmTKkY0r1rI2Z4nixwHaIy?pid=ImgDet&rs=1",  heading:"Ajith Kumar" ,extrecom:" Ajith became a racing driver, competing in circuits around India in places such as Mumbai, Chennai and Delhi. He is one among very few Indians to race in the International arena and in Formula championships. He has also been abroad for various races, including Germany and Malaysia. He drove in the 2003 Formula Asia BMW Championships.[8] He raced in the 2010 Formula 2 Championship along with two other Indians, Armaan Ebrahim and Parthiva Sureshwaren.[9]",command:"Ajith Kumar is an Indian actor who works predominantly in Tamil cinema. To date, he has starred in over 61 films, and his awards include four Vijay Awards, three Cinema"}, 
      {id:36,icon:"Bollywood", cat:"bollywoodbott", img:"https://th.bing.com/th/id/R.4a330094ede8b209790af045b9b84dc4?rik=6vinDk1NpgDPNQ&riu=http%3a%2f%2f3.bp.blogspot.com%2f-FqCefXkDeMQ%2fTzueaHuAHAI%2fAAAAAAAACoU%2fv2QZoHUHjX4%2fs1600%2fTrisha%2bLatest%2bHot%2bPhotos%2b3.jpg&ehk=5E59koRP9pj6HxOAofezK5u5MbrckP%2b8C9RU9Ab9rLw%3d&risl=&pid=ImgRaw&r=0", heading:"Trisha Krishnan " ,extrecom:"Later in 2004, she acted as the female lead opposite Vijay in the action comedy film Ghilli. She played the character of Dhanalakshmi, a helpless girl who is protected from a thug by a Kabaddi player. However, most critics agreed that her performance in this film was overshadowed by Vijay and Prakash Raj.[43][44] The film eventually emerged as the highest-grossing Tamil film of the year, celebrating a 175-day run,[45][46] and was Trisha's biggest commercial success at the time. She next appeared in a small role in Mani Ratnam's political drama Aayutha Ezhuthu (2004), starring as part of an ensemble cast that included Siddharth, Madhavan and Surya. The film, despite favourable reviews, performed poorly at the box office, and she was once again outshone by the three male lead actors.",command:"Trisha Krishnan (born 4 May 1983) is an Indian model and actress who works predominantly in Tamil and Telugu films."},
      {id:37,icon:"Bollywood", cat:"bollywoodbott", img:"https://tse3.mm.bing.net/th/id/OIP.IbpySuAOWirLyfD4d0xQ5wHaKX?pid=ImgDet&rs=1",  heading:"Nayanthara " ,extrecom:"She began her acting career in 2003 with the Malayalam film Manassinakkare.While studying at college, Nayanthara worked part-time as a model.[23][24] She was spotted by director Sathyan Anthikkad, who had seen some of her modelling assignments and approached her to play a pivotal role in his film Manassinakkare (2003).[23] Although she turned down the offer initially, as she was not interested in films, she gave in eventually and agreed to do just that one film.[23] Manassinakkare went on to become a big financial success and she continued to receive acting offers. Both her releases in 2004, Natturajavu by Shaji Kailas, and Fazil's psychological thriller Vismayathumbathu, saw her co-starring alongside Mohanlal; while she played the protagonist's adopted sister in the former, she portrayed a ghost in the latter.[25] Her performance in Vismayathumbathu, in particular, was lauded, with critics claiming that she had stolen the thunder with her author-backed role ",command:"Diana Mariam Kurian (born 18 November 1984), known professionally as Nayanthara, is an Indian actress and film producer who predominantly appears in Tamil, Malayalam and Telugu films"},
     
     
      {id:38,icon:"hollywood" ,cat:"hollywood", img:"https://tse4.mm.bing.net/th/id/OIP.pBb3u1GMUBn2rCDSvU77ugHaHa?w=165&h=180&c=7&r=0&o=5&dpr=1.6&pid=1.7", heading:"Avengers" ,extrecom:"Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the direct sequel to Avengers: Infinity War (2018) and the 22nd film in the Marvel Cinematic Universe (MCU). Directed by Anthony and Joe Russo and written by Christopher Markus and Stephen McFeely, the film features an ensemble cast including Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Benedict Wong, Jon Favreau, Bradley Cooper, Gwyneth Paltrow, and Josh Brolin. In the film, the surviving members of the Avengers and their allies attempt to reverse Thanos's actions in Infinity War. ",command:"The Avengers are a team of fictional superheroes and the protagonists of the Marvel Cinematic Universe (MCU) media franchise, based on the Marvel Comics team of the same name created by Stan Lee and Jack Kirby in 1963."},
      {id:39,icon:"hollywood" ,cat:"hollywood", img:"https://1.bp.blogspot.com/--joETLmICOw/X45xmNWLATI/AAAAAAAAblc/-iwRayzauKIGsiBGQ5gUfG_lzlOL-wURwCLcBGAsYHQ/w1200-h630-p-k-no-nu/marvels-avengers-cover.webp", heading:"The Avengers Initiative",extrecom:"The film was announced in October 2014 as Avengers: Infinity War – Part 2, but Marvel later removed this title. The Russo brothers joined as directors in April 2015, with Markus and McFeely signing on to write the script a month later. The film serves as a conclusion to the story of the MCU up to that point, ending the story arcs for several main characters. The plot revisits several moments from earlier films, bringing back actors and settings from throughout the franchise. Filming began in August 2017 at Pinewood Atlanta Studios in Fayette County, Georgia, shooting back-to-back with Infinity War, and ended in January 2018. Additional filming took place in the Metro and Downtown Atlanta areas, the state of New York, Scotland, and England. The official title was revealed in December 2018. With an estimated budget of $356–400 million, the film is one of the most expensive films ever made. ",command:"In 1995, S.H.I.E.L.D. director Nick Fury creates the Avengers Initiative, envisioning it as a group of heroes working to respond to planetary threats, following the appearance of Carol Danvers and naming it after her U.S. Air Force callsign"},
      {id:40, icon:"hollywood" ,cat:"hollywood", img:"https://i.redd.it/ernhxu7mgxp01.jpg", heading:"The first assembly",extrecom:"Avengers: Endgame premiered in Los Angeles on April 22, 2019, and was released in the United States on April 26, as part of Phase Three of the MCU. The film received praise for its direction, acting, musical score, action sequences, visual effects, and emotional weight, with critics lauding its culmination of the 22-film story. The film grossed $2.799 billion worldwide, surpassing Infinity War's entire theatrical run in just eleven days and breaking numerous box office records, including becoming the highest-grossing film of all time from July 2019 until March 2021. It received a nomination for Best Visual Effects at the 92nd Academy Awards, among numerous other accolades. Fifth and sixth Avengers films, titled Avengers: The Kang Dynasty and Avengers: Secret Wars, respectively, are scheduled to be released in 2026 and 2027. ",command:"In 2012, the Asgardian Loki teleports to the Joint Dark Energy Mission Facility on Earth, where he steals the Tesseract and brainwashes Clint Barton and Dr. Erik Selvig using his scepter. "},    
      {id:41,icon:"hollywood" , cat:"hollywood", img:"https://upload.wikimedia.org/wikipedia/en/f/f2/Robert_Downey_Jr._as_Tony_Stark_in_Avengers_Infinity_War.jpg", heading:"Battle of New York",extrecom:"In 2018, twenty-three days after Thanos erased half of all life in the universe,[a] Carol Danvers rescues Tony Stark and Nebula from deep space and they reunite with the remaining Avengers—Bruce Banner, Steve Rogers, Thor, Natasha Romanoff, and James Rhodes—and Rocket on Earth. Locating Thanos on an uninhabited planet, they plan to use the Infinity Stones to reverse his actions, but discover Thanos has already destroyed them to prevent further use. Enraged, Thor decapitates Thanos. ",command:"After Loki kills S.H.I.E.L.D. agent Phil Coulson, the team unites to avenge him. Romanoff frees Barton from the scepter's control, and the Avengers confronts Loki, who opens a wormhole using the Tesseract and begins his invasion with his Chitauri army. "},
      {id:42,icon:"hollywood" ,num:"2",  cat:"hollywoodtop", img:"https://static3.srcdn.com/wordpress/wp-content/uploads/Avengers-2-Team-Wallpaper-Audi-Promo-Image.jpg", heading:"Fighting Hydra and Ultron",extrecom:"Five years later, Scott Lang escapes from the Quantum Realm.[b] Reaching the Avengers Compound, he explains that he experienced only five hours while trapped. Theorizing that the Quantum Realm allows time travel, they ask a reluctant Stark to help them retrieve the Stones from the past to reverse the actions of Thanos in the present. Stark, Rocket, and Banner, who has since merged his intelligence with the Hulk's strength, build a time machine. Banner notes that altering the past does not affect their present; any changes create alternate realities. Banner and Rocket travel to Norway, where they visit the Asgardian refugees' settlement New Asgard and recruit an overweight and despondent Thor. In Tokyo, Romanoff recruits Clint Barton, who became a vigilante after his family was erased during the execution of Thanos' plan. ",command:"Three years after the Battle of New York, Hydra uses Loki's scepter following their infiltration of S.H.I.E.L.D."},
      {id:43,icon:"hollywood" ,num:"3",  cat:"hollywoodtop", img:"https://hdqwalls.com/download/1/thor-avengers.jpg", heading:"Battle of Sokovia" ,extrecom:" Banner, Lang, Rogers, and Stark time-travel to New York City during Loki's attack in 2012.[c] At the Sanctum Sanctorum, Banner convinces the Ancient One to give him the Time Stone after promising to return the various Stones to their proper points in time. At Stark Tower, Rogers retrieves the Mind Stone from Hydra sleeper agents, but Stark and Lang's attempt to steal the Space Stone fails, allowing 2012-Loki to escape with it. Rogers and Stark travel to Camp Lehigh in 1970, where Stark obtains an earlier version of the Space Stone and encounters his father, Howard. Rogers steals Pym Particles from Hank Pym to return to the present and spies his lost love, Peggy Carter.",command:"Ultron tries to use Sokovia as a meteor to induce an extinction event. "},    
      {id:44,icon:"hollywood" ,num:"4",  cat:"hollywoodtop", img:"https://images3.alphacoders.com/605/605991.jpg", heading:"Civil War",extrecom:"Meanwhile, Rocket and Thor travel to Asgard in 2013;[d] Rocket extracts the Reality Stone from Jane Foster, while Thor gets encouragement from his mother, Frigga, and retrieves his old hammer, Mjolnir. Barton, Romanoff, Nebula, and Rhodes travel to 2014; Nebula and Rhodes go to Morag and steal the Power Stone before Peter Quill can,[e] while Barton and Romanoff travel to Vormir. The Soul Stone's keeper, Red Skull, reveals it can only be acquired by sacrificing a loved one. Romanoff sacrifices herself, allowing Barton to get the Stone. Rhodes and Nebula attempt to return to their own time, but Nebula is incapacitated when her cybernetic implants link with her past self, allowing 2014-Thanos to learn of his future self's success and the Avengers' attempt to undo it. 2014-Thanos sends 2014-Nebula forward in time to prepare for his arrival. ",command:"Months after the Battle of Sokovia, the Avengers' new facility becomes targeted in a heist, with a skirmish between Wilson and Scott Lang."},
      // {id:44,icon:"hollywood" ,num:"5",  cat:"hollywoodtop", img:"https://tse2.mm.bing.net/th/id/OIP.OuKaX22FXVX827YXNMR0HgHaEK?pid=ImgDet&rs=1", heading:" War",extrecom:"Reuniting in the present, the Avengers place the Stones into a gauntlet that Stark, Banner, and Rocket have built. Having the most resistance to their radiation, Banner wields the gauntlet and reverses Thanos's disintegrations. Meanwhile, 2014-Nebula, impersonating her future self, uses the time machine to transport 2014-Thanos and his warship to the present, which he then uses to destroy the Avengers Compound. Present-day Nebula convinces 2014-Gamora to betray Thanos, but is unable to convince 2014-Nebula and kills her. Thanos overpowers Stark, Thor, and a Mjolnir-wielding Rogers and summons his army to retrieve the Stones, intent on using them to destroy the universe and create a new one. A restored Stephen Strange arrives with other sorcerers, the restored Avengers and Guardians of the Galaxy, the Ravagers, and the armies of Wakanda and Asgard to fight Thanos's army. Danvers also arrives and destroys Thanos's warship, but Thanos overpowers her and seizes the gauntlet. Stark steals the Stones and uses them to disintegrate Thanos and his army, at the cost of his life. ",command:" The Avengers' new facility becomes targeted in a heist, with a skirmish between Wilson and Scott Lang."},
      {id:73,icon:"hollywood" ,  cat:"newtoptechholly", img:"https://letsdownloadgame.com/wp-content/uploads/2019/12/Download-marvels-avengers-game-apk-for-android-free.jpg", heading:"The Avengers",extrecom:"Avengers: Age of Ultron is a 2015 American superhero film based on the Marvel Comics superhero team the Avengers. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the sequel to The Avengers (2012) and the 11th film in the Marvel Cinematic Universe (MCU). Written and directed by Joss Whedon, the film features an ensemble cast including Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Scarlett Johansson, Jeremy Renner, Don Cheadle, Aaron Taylor-Johnson, Elizabeth Olsen, Paul Bettany, Cobie Smulders, Anthony Mackie, Hayley Atwell, Idris Elba, Linda Cardellini, Stellan Skarsgård, James Spader, and Samuel L. Jackson. In the film, the Avengers fight Ultron (Spader)—an artificial intelligence created by Tony Stark (Downey) and Bruce Banner (Ruffalo) who plans to bring about world peace by causing human extinction. ",num:"1",command:"Bioluminescence imaging, a technique for studying laboratory animals using luminescent protein"},
     
      {id:45,icon:"hollywood" , cat:"hollywood", img:"https://images.hdqwalls.com/wallpapers/avengers-iron-man-4k-b3.jpg", heading:"Play Reassemble First" ,extrecom:"The sequel was announced in May 2012 after the successful release of The Avengers, with Whedon set to return as writer and director in August. Whedon updated Ultron's origin for the film to involve the MCU's Avengers team, and introduced the characters Pietro (Taylor-Johnson) and Wanda Maximoff (Olsen) to whom Marvel shared the rights with 20th Century Fox. Casting began in June 2013 with the re-signing of Downey. Second unit filming began in February 2014 in South Africa with principal photography taking place between March and August, primarily at Shepperton Studios in Surrey, England. Additional footage was filmed in Italy, South Korea, Bangladesh, the state of New York, and around England. With an estimated net production budget of $365 million, the film is one of the most expensive films ever made. ",command:"When you boot up Marvel's Avengers, you'll have the choice of playing Reassemble or Avengers Initiative. The former is the single-player campaign"},
      {id:46, icon:"hollywood" ,cat:"hollywood", img:"https://tse2.mm.bing.net/th/id/OIP.OuKaX22FXVX827YXNMR0HgHaEK?pid=ImgDet&rs=1", heading:"Fill That Stun Meter",extrecom:"In the Eastern European country of Sokovia, the Avengers—Tony Stark, Thor, Bruce Banner, Steve Rogers, Natasha Romanoff, and Clint Barton—raid a Hydra facility commanded by Baron Wolfgang von Strucker, who has experimented on humans using the scepter previously wielded by Loki. They meet two of Strucker's test subjects—twins Pietro (who has superhuman speed) and Wanda Maximoff (who has telepathic and telekinetic abilities)—and apprehend Strucker, while Stark retrieves Loki's scepter. ",command:"As a follow-up, you don't have to worry too much about your gear and power level in the Reassemble campaign."},
     
      {id:47,icon:"technology" , cat:"Reactjs", img:"https://wallpapercave.com/wp/wp4923992.png", heading:" Reactjs" ,extrecom:"React adheres to the declarative programming paradigm. Developers design views for each state of an application, and React updates and renders components when data changes. This is in contrast with imperative programming.React Bootstrap CSS was created with compatibility in mind: bootstrap core compatibility and the world’s largest UI ecosystem compatibility. ",command:"Animation in ReactJs app is a popular topic and there are many ways to create different types of animations.Many developers create animation exclusively using css and adding classes to HTML tags.This is a great way and you should use it. If you want to create complex animations you can pay attention to GreenSock. GreenSock is the most powerful animation platform. There are also a lot of libraries, components for creating animation in React."},
      {id:48,icon:"technology" ,  cat:"Reactjsscr", img:"https://i.pinimg.com/originals/e4/53/0c/e4530ccfa55c4756444777672f51b125.png", heading:"React js working page" ,extrecom:"React JS doesn’t support the feature of server-side applications. React JS sends the Ajax request to send and receive the data through the API.React uses an HTML-in-JavaScript syntax called JSX (JavaScript and XML). Familiarity with both HTML and JavaScript will help you to learn JSX, and better identify whether bugs in your application ",command:"It is a JavaScript syntax extension popularized by React. Putting JSX markup close to related rendering logic makes React components easy to create, maintain, and delete"},
      {id:49,icon:"technology" ,  cat:"technology", img:"https://s3-ap-south-1.amazonaws.com/trt-blog-ghost/2023/01/Mean-Tech-stack.png", heading:"MEAN STACK",extrecom:"That’s where MongoDB comes in: JSON documents created in your Angular.js front end can be sent to the Express.js server, where they can be processed and (assuming they’re valid) stored directly in MongoDB for later retrieval. who want to design the dynamic website and web application using Mean.js. Our tutorial covers all the components of Mean.js, such as MongoDB, Express.js, Node.js,",command:"The mean stack tutorial is designed for the developers  "},
      {id:50,icon:"technology" ,  cat:"technology", img:"https://assets-global.website-files.com/6410ebf8e483b5bb2c86eb27/6410ebf8e483b53d6186fc53_ABM%20College%20Web%20developer%20main.jpg", heading:"Web development" ,extrecom:" Web development is the work involved in developing a website for the Internet (World Wide Web) or an intranet (a private network).[1] Web development can range from developing a simple single static page of plain text to complex web applications, electronic businesses, and social network services. A more comprehensive list of tasks to which Web development commonly refers, may include Web engineering, Web design, Web content development, client liaison, client-side/server-side scripting, Web server and network security configuration, and e-commerce development.(World Wide Web) or an intranet (a private network). Web development can range from developing a simple single static page of plain text to complex web applications. ",command:"Web development is the work involved in developing a website for the Internet "},
      {id:50,icon:"technology" ,  cat:"technology",  img:"https://tse4.mm.bing.net/th/id/OIP.piQ-UxF9O_5EaSj6NtOKIAHaFr?pid=ImgDet&rs=1", heading:"HTML " ,extrecom:" Web development is the work involved in developing a website for the Internet (World Wide Web) or an intranet (a private network).[1] Web development can range from developing a simple single static page of plain text to complex web applications, electronic businesses, and social network services. A more comprehensive list of tasks to which Web development commonly refers, may include Web engineering, Web design, Web content development, client liaison, client-side/server-side scripting, Web server and network security configuration, and e-commerce development.(World Wide Web) or an intranet (a private network). Web development can range from developing a simple single static page of plain text to complex web applications. ",command:"Web development is the work involved in developing a website for the Internet "},
     
      {id:51,icon:"technology" ,  cat:"technology", img:"https://miro.medium.com/v2/resize:fit:678/1*l2tlJsFNg2tH6QizegKkqA.png", heading:"MERN Stack ",extrecom:"If your application stores any data (user profiles, content, comments, uploads, events, etc.), then you’re going to want a database that’s just as easy to work with as Angular, Express, and Node. after the four key technologies that make up the stack. 1. MongoDB — document database 2. Express(.js) — Node.js web framework  ",command:"MERN stands for MongoDB, Express, React, Node, "},
      {id:52,icon:"technology" ,  cat:"technology", img:"https://mobisoftinfotech.com/resources/wp-content/uploads/2022/06/og-Best-Practices-for-Android-Development.png", heading:"Android Development",extrecom:"Beta 5 is our third Platform Stable Android 14 release, which means that the developer APIs and all app-facing behaviors are final for you to review and integrate into your apps, and you can publish apps on Google PlayWe’re excited to announce that version 1.2 of Compose for Wear OS and Wear Tiles libraries have reached the stable milestone. This makes it easier than ever to use these modern APIs to build beautiful and engaging kernel and other open-source software, designed primarily for touchscreen mobile devices such as smartphones and tablets. …",command:"Android is a mobile operating system based on a modified version of the Linux "},
      {id:53,icon:"technology" ,  cat:"newtoptech",num:"1", img:"https://tse2.mm.bing.net/th/id/OIP.HNS0WSdJ8yqN9gCOBNBtLwHaFj?pid=ImgDet&w=700&h=525&rs=1", heading:"Bioluminescence",extrecom:"The light emitted by a bioluminescent organism is produced by energy released from chemical reactions occurring inside (or ejected by) the organism.If you’ve ever seen a firefly, you have encountered a bioluminescent organism. In the ocean, bioluminescence is not as rare as you might think. In fact, most types of animals, from bacteria to sharks, include some bioluminescent members. ",command:"Bioluminescence imaging, a technique for studying laboratory animals using luminescent protein"},
      // {id:54,icon:"technology" ,  cat:"the latesttech",heading:"HTML " ,extrecom:"that is used to structure a web page and its content. For example, content could be structured within a set of paragraphs, a list of bulleted points, or using images and data tables.HTML provides the content that gives web pages structure, by using elements and tags, you can add text, images, videos, forms, and more. Learning HTML basics is an important first step in your web development journey and an essential skill for front- and back-end developers. ",command:" The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser."},
      {id:55,icon:"technology" ,  cat:"the latesttech", img:"https://tse4.mm.bing.net/th/id/OIP.tAvAD5lCtDJSjywplxd37QHaEo?pid=ImgDet&rs=1", heading:" CSS " ,extrecom:" The “cascading” in CSS refers to the fact that styling rules “cascade” down from several sources. This means that CSS has an inherent hierarchy and styles of a higher precedence will overwrite rules of a lower precedence.A CSS Syntax rule consists of a selector, property, and its value. The selector points to the HTML element where the CSS style is to be applied. The CSS property is separated by semicolons. It is a combination of the selector name followed by the property: value pair that is defined for the specific selector.",command:"Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation MathML or XHTML)."},
      {id:55, icon:"technology" , cat:"the latesttech", img:"https://wallpapercave.com/wp/wp4923992.png", heading:" React JS " ,extrecom:" Create React App. To learn and test React, you should set up a React Environment on your computer. This tutorial uses the create-react-app. The create-react-app tool is an officially supported way to create ReactReactJS is a declarative, efficient, and flexible JavaScript library for building reusable UI components. It is an open-source, component-based front end library which is responsible only for the view layer of the application. It was initially developed and maintained by Facebook and later used in its products like WhatsApp & Instagram.",command:"It is a JavaScript syntax extension popularized by React. Putting JSX markup close to related rendering  and delete."},
    
      {id:56,icon:"technology" ,  cat:"the latesttech", img:"https://th.bing.com/th/id/R.ff60b397fc71f93ab8db2edd234d43b0?rik=Sf1RQ1AvcSRbew&riu=http%3a%2f%2f2.bp.blogspot.com%2f-1lsXAuaZ5Cs%2fVLi5g8nQTmI%2fAAAAAAAACEs%2fKZdJRzgVP9Q%2fs1600%2fjavascript-logo-png.png&ehk=V2zOCpWiVFmy5Cvz%2fSqe2kmDWDe79WkeJmisw7e8RVQ%3d&risl=&pid=ImgRaw&r=0", heading:"JavaScript",extrecom:" JavaScript , often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2023, 98.7% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries. All major web browsers have a dedicated JavaScript engine to execute the code on users' devices.",command: "JavaScript is one of the 3 languages all web developers mustlearn: 1. HTMLto define the content of web pages "},
      {id:57,icon:"technology" ,  cat:"technologytop", img:"https://builtin.com/sites/www.builtin.com/files/styles/og/public/2022-09/biotech.png",num:'2',heading:"DNA-Human DNA is 94% to 98% identical to the DNA",extrecom:"Human DNA is 94% to 98% identical to the DNA of chimpanzees. That’s quite understandable but what’s shocking is that human DNA is 50% identical to the DNA of bananas!Molecules of DNA range in length from hundreds of thousands to millions of base pairs. The smallest chromosome in the human genome, Chromosome 21, has around 48 million base pairs. ",command:"Deoxyribonucleic acid is a polymer composed of two polynucleotide chains "},
      {id:58,icon:"technology" ,  cat:"technologytop",num:'3', img:"https://gumlet.assettype.com/swarajya%2F2020-08%2F7f5acda4-8891-49fc-9f28-f339d0b98c23%2FAg_tech.jpeg?q=75&auto=format%2Ccompress&w=1200",heading:"Green plants, ranging in size from microscopic",extrecom:" Green plants, ranging in size from microscopic to some 100 metres tall, obtain most of their energy from sunlight, using chloroplasts derived from endosymbiosis with cyanobacteria. Chloroplasts perform photosynthesis, making sugars from carbon dioxide and water, using the pigment chlorophyll, which gives them their green colour. Some plants are parasitic, deriving their energy from other plants, and have lost the ability to produce normal amounts of chlorophyll or to photosynthesize. Plants are characterized by sexual reproduction and alternation of generations, but asexual reproduction is also common.      ",command:"Plants are eukaryotes, predominantly photosynthetic, that form the kingdom"},
      {id:59,icon:"technology" ,  cat:"technologytop",num:'4', img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHGK68uXmwGcCSP2ZZQo9Ftq8OAV0ndYJPiQ&usqp=CAU",heading:"chloroplasts derived from endosymbiosis . ",extrecom:" Green plants, ranging in size from microscopic to some 100 metres tall, obtain most of their energy from sunlight, using chloroplasts derived from endosymbiosis with cyanobacteria. Chloroplasts perform photosynthesis, making sugars from carbon dioxide and water, using the pigment chlorophyll, which gives them their green colour. Some plants are parasitic, deriving their energy from other plants, and have lost the ability to produce normal amounts of chlorophyll or to photosynthesize. Plants are characterized by sexual reproduction and alternation of generations, but asexual reproduction is also common.      ",command:"Biotechnology is a multidisciplinary field that involves the integration of natural sciences  "},
      {id:60,icon:"technology" ,  cat:"technology", img:"https://tse2.mm.bing.net/th/id/OIP.PeOMGrlVHERogA8T6mBDhgHaFj?pid=ImgDet&rs=1", heading:"AngularJS ",extrecom:"HTML is great for declaring static documents, but it falters when we try to use it for declaring dynamic views in web-applications. AngularJS lets you extend HTML vocabulary for your application. The resulting environment is extraordinarily expressive, readable, and quick to develop.Data-binding is an automatic way of updating the view whenever the model changes, as well as updating the model whenever the view changes. This is awesome because it eliminates DOM manipulation from the list of things you have to worry about. ",command:"This tutorial is specially designed to help you learn AngularJS as quickly and efficiently as possible. "},
      
      // {id:61,icon:"fitness" ,  cat:"fitnesstop", img:"https://asset-eu.unileversolutions.com/content/dam/unilever/rexona/global/general_image/deodorants_and_fragrances/not_applicable/1_2_people_jumping_up_off_a_short_wall_1209x723-889036.jpg.ulenscale.669x400.jpg" ,heading:"Keep Your Portions in Check",extrecom:"Other tips include ordering a side salad or vegetables, asking for sauces and dressings to be served separately and avoiding buffet-style, all-you-can-eat restaurants where it’s very easy to overindulge. ",command:"Portion control requires special attention to your current eating habits. For example, if your steak takes up"},
      {id:62,icon:"fitness" ,num:"2",   cat:"fitnesstop", img:"https://tse2.mm.bing.net/th/id/OIP.iX9N_n4RxTY5ryb192sqlgHaE7?pid=ImgDet&rs=1" ,heading:"Sip Slowly",extrecom:"Health and fitness is really means a lot to our life. Students including all the growing age children must know the importance of health and fitness. In order to improve their knowledge about health and fitness as well as improve the skill of English writing, teachers assign them to write paragraphs on health and fitness. Students studying in classes 1, 2, 3, 4 or 5 get assigned to write paragraph on health and fitness by their class teacher. ",command:"If you know you'll be partaking in more than one drink, try to order a glass of water between cocktails, said Newgent."},
      {id:63,icon:"fitness" ,num:"3",   cat:"fitnesstop", img:"https://tse3.mm.bing.net/th/id/OIP.vvQp9cH2qQrOVoApUOuhwAHaEK?pid=ImgDet&rs=1" ,heading:"Work Out Consistently",extrecom:" We have provided below some health and fitness paragraphs to help students. They can choose any paragraph according to their need and requirement. All the health and fitness paragraphs are written in easy words and simple sentences.",command:"Working out at the same time during the week or on the same days can have its benefits."},
      {id:64,icon:"fitness" ,num:"4",   cat:"fitnesstop", img:"https://www.muscleandfitness.com/wp-content/uploads/2019/10/women-squat-home-workout-1109.jpg?w=1100&quality=86&strip=all" ,heading:"Up Your Fiber Intake",extrecom:"Both, health and fitness are closely inter-related to each other. Both are necessary for the human being to live a happy and healthy life. There are various things we have to take care all through the life in order be healthy and fit. There is no alternate to the health and fitness, we have to eat healthy food timely, do physical exercises daily, think positive and have patience and commitment towards good lifestyle. ",command:"Along with protein and healthy fats, fiber is one of those nutritional elements that keeps you full and fueled all day long"},
      {id:65,icon:"fitness" ,   cat:"fitness", img:"https://th.bing.com/th/id/R.e165b8e3f2d4d7757300f76790408dbb?rik=QOeYp%2b7JeQixaw&riu=http%3a%2f%2fwww.pixelstalk.net%2fwp-content%2fuploads%2f2016%2f06%2fBest-HD-Fitness-Backgrounds.jpg&ehk=0YyKEvL%2baTbWC8ceGZ5dFmdg%2biBqAixipIQ4PogMWT4%3d&risl=&pid=ImgRaw&r=0", heading:"Stock Your Fridge with Healthy Foods " ,extrecom:"Physically exercises are great for our muscles, heart, and lungs. Some more advantages of the physical activities are; it builds our bones strong, saves us from obesity by promoting a healthy weight, saves us from diabetes, helps us to build healthy habits, keeps us away from cancer, prevents high blood pressure, and other major problems. Thus, through regular exercises and healthy food in timely manner, we can easily maintain our health and fitness.      ",command:"Foods like fruits, vegetables, and lean meats can go a long way for your fitness journey."},
      // {id:66,icon:"fitness" ,   cat:"fitness", img:"https://4.bp.blogspot.com/-wNP5HrQ4kkM/WLLpm83qvzI/AAAAAAAAAJY/YxFLCSsszv4e03HauzgE5vg5n5XdXnACACEw/s1600/5%2BComponents%2Bof%2BPhysical%2BFitness%2B01.jpg", heading:"Find a Workout Buddy ",extrecom:" Being involved in physical activities on daily basis does something great to our body and mind. It makes us feel good, helps us to complete tough tasks, makes us pleasant all around and keeps us happy all time because our body releases a chemical called endorphins while we involved in the physical activities. Regular physical activities also reduces stress, improves sleep, boosts energy level, reduces symptoms of anxiety and depression, increases our self-esteem, makes us feel proud, improves confidence level and personality, etc. ",command:"A friend you can work out with is very helpful for staying motivated, but it's important to find someone who will inspire—not discourage."},
      // {id:67,icon:"fitness" ,   cat:"fitness", img:"https://yegfitness.ca/wp-content/uploads/2020/06/Diet-and-Exercise-Tips.jpg", heading:"Stay Hydrated ",extrecom:" Being healthy means not only away from diseases but it also means the complete feeling of physical, mental and social well being. Maintaining health and fitness is not a simple task however; not so tough too. We need to involve ourselves into some daily physical activities together with the healthy, fresh and timely food which can only provide us long-term health and fitness benefits. We burn extra and unnecessary calories to our body through physical exercises. Daily physical exercises keep kids so active and put them on a path of better physical and mental health.",command:"Whether you're heading off to spin class, boot camp, or any other exercise class, it's always important to hydrate so you can stay energized and have your best workout. "},
      {id:68,icon:"fitness" ,   cat:"fitness", img:"https://tse4.mm.bing.net/th/id/OIP.A9sDjPjLXHPDdHOdu1XQEgHaEK?pid=ImgDet&rs=1", heading:"Relieve Those Achy Muscles ",extrecom:"Physical activities along with the proper nutrition are really very beneficial to the people of all ages from any background and abilities. Being involved in the daily physical exercises is a good strategy to defeat obesity. According to the statistics, it is found that around one-third of the U.S. adult citizens are obese and almost 17% of children and adolescents are obese. There are many people suffering from the diabetes and other chronic health problems such as heart disease, high blood pressure, cancer, asthma, overweight, etc. ",command:"After a grueling workout, there's a good chance you're going to be feeling sore thighs and tight calves."},
      {id:69,icon:"fitness" ,   cat:"fitness", img:"https://tse4.mm.bing.net/th/id/OIP.knN0NxWLuwuqLNgSGbJXAwHaE7?pid=ImgDet&w=1160&h=773&rs=1", heading:"Curb Your Sweet Tooth ",extrecom:" We can be fit just by incorporating some physical activities including healthy eating to our daily life for 30 minutes (for adults) and 60 minutes (for children). Regular physical activities help us to get long-term health benefits through:",command:"Cutting down on sugar can assist you with weight loss—individuals who consume less sugar end up with lower weights"},
      {id:70,icon:"fitness" ,   cat:"fitness", img:"https://thumbs.dreamstime.com/b/multiethnic-group-people-training-gym-trainer-sportive-fit-persons-exercising-multiethnic-group-people-training-262162888.jpg", heading:"Wear Comfortable Sneakers ",extrecom:"Around 30 or above 30, our body starts developing various health problems if we are not involved in any type of physical activity. In such case, we are at tip of risks who must think about the health and fitness as well as starts following all the tips of getting healthy and fit. Physical exercises and proper nutrition on daily basis gives us health, physical fitness and mental fitness. ",command:"Your feet swell during the day and stop in the late afternoon, so if you need sneakers, you'll want to shop when your feet are biggest. "},
      {id:71,icon:"fitness" ,   cat:"newtopfit", img:"https://img.favpng.com/16/18/6/vector-creative-fitness-logo-png-favpng-Aqsd61AfedTqieGT9uu1NPsHz.jpg  ", heading:"Pick Your Perfect Tunes",extrecom:". In order to maintain a healthy lifestyle, we must involve in the daily routine exercises and fresh healthy food. Being healthy and fit increases our energy level, improves confidence, burns calories, minimizes complications of chronic diseases and increases life term. ",num:"1",command:"Running with music is a great way to get in a good workout groove. To pick the ultimate playlis."},
      {id:72,icon:"fitness" ,   cat:"newtopfit2", img:"https://www.paridhiwebtech.com/health-fitness/img/img09.jpg", heading:"Know When To Weigh Yourself—And How Often",extrecom:"In order to maintain health and fitness, we must be self motivated and encouraged. We must use all the moves which can motivate us. There is necessity of at least 2.5 hours (moderate-intensity) or 1.25 hours (vigorous-intensity) aerobic physical activities in a week. For getting more health benefits, we need to increase our moderate-intensity aerobic physical activity up to 5 hours or vigorous-intensity aerobic physical activity up to 2.5 hours in a week. Physical activity should be the essential part of our life in order to be fit, healthy and young. ",command:" It's normal to want to weigh yourself soon after starting a new diet or fitness routine. It's best to step on the scale , said Newgent. "},
      
     {id:73,icon:"hollywood" ,   cat:"newtophollywood", img:"https://letsdownloadgame.com/wp-content/uploads/2019/12/Download-marvels-avengers-game-apk-for-android-free.jpg", heading:"The Avengers",extrecom:"Avengers: Age of Ultron is a 2015 American superhero film based on the Marvel Comics superhero team the Avengers. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the sequel to The Avengers (2012) and the 11th film in the Marvel Cinematic Universe (MCU). Written and directed by Joss Whedon, the film features an ensemble cast including Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans, Scarlett Johansson, Jeremy Renner, Don Cheadle, Aaron Taylor-Johnson, Elizabeth Olsen, Paul Bettany, Cobie Smulders, Anthony Mackie, Hayley Atwell, Idris Elba, Linda Cardellini, Stellan Skarsgård, James Spader, and Samuel L. Jackson. In the film, the Avengers fight Ultron (Spader)—an artificial intelligence created by Tony Stark (Downey) and Bruce Banner (Ruffalo) who plans to bring about world peace by causing human extinction.  ",command:"The concept of the Avengers was teased in the post-credits scene of Iron Man (2008), the first MCU film, by Nick Fury as an initiative created by him. The concept was further explored in Iron Man 2 (2010), with the introduction of Natasha Romanoff."},
      {id:73,icon:"food", cat:"newtopfood", img:"https://www.verywellfit.com/thmb/WY_NtJB9XE1wZTaKbk2syDPITUc=/3865x2576/filters:fill(FFDB5D,1)/different-types-of-food-on-rustic-wooden-table-861188910-5bd1d6f846e0fb00519d99f9.jpg", heading:"Don’t eat heavily charred meats",num:"1",extrecom:"Finally, don’t forget to proofread! Even if you’re just publishing on a personal blog, error-free writing will be easier to read, look more professional, and attract more readers. And if you plan to submit your writing to a magazine or publisher, you need it to be the best it can be! ",command:"Meat can be a nutritious and healthy part of your diet. It’s very high in protein and a rich source of nutrient "},
      {id:74,icon:"fitness" ,   cat:"fitness", img:"https://mahogany360fitness.com/wp-content/uploads/2021/01/about-fitness-img.png", heading:"Use Sunscreen for Outdoor Workouts",extrecom:"Physical fitness is really very much important in our life. Now-a-days, in the modern life, most of the people are moving towards more sedentary lifestyle which is increasing the risk of diseases because of reduced daily activity level, bad cardiovascular fitness and increased body weight. People, who are involved in the inactive lifestyle, must know the benefits of health and physical fitness so that they can involve themselves in the daily routine physical exercises in order to remain away from diseases and be fit.      ",command:"Getting the fresh air from exercising outdoors is great, but along with it, you also get harmful UV rays."},
      {id:75,icon:"fitness" ,   cat:"fitness", img:"https://tse3.mm.bing.net/th/id/OIP.gk3BbnKEgWdj4PXKRAXi1QHaEK?pid=ImgDet&w=602&h=339&rs=1", heading:"Savor Your Carbs ",extrecom:" Being active is very necessary for keeping our body functioning at a high level. Regular physical exercises help in maintaining the performance of lungs, heart and other major body organs. It burns off excess calories and keeps our weight under control. It also improves the muscle and bone strength, increases the joint flexibility as well as improves muscle endurance. Most importantly, daily physical activities decrease the risk of heart diseases, risk of stroke, diabetes, high blood pressure, colon cancer, etc.",command:"At times, you may consider cutting out your carbs to lose weight. But before adding dinner rolls and chips "},
      {id:76,icon:"food", cat:"food", img:"https://www.lecremedelacrumb.com/wp-content/uploads/2016/01/baked-honey-mustard-chicken-1w.jpg", heading:"Limit sugary drinks      " ,extrecom:"Never describe food as bizarre, strange, odd, unusual, abnormal, or weird. Just because a flavor profile is uncommon in Western cuisine doesn’t make it obscure, and having good intentions when using these words doesn’t erase their negative impact. are the primary source of added sugar in the American diet ",command:"Sugary drinks like sodas, fruit juices, and sweetened teas "},
      {id:77,icon:"food", cat:"food", img:"https://4.bp.blogspot.com/-Xrxd-8idowk/UpI1z1jgw9I/AAAAAAAAACA/B_M6GbopQzc/s1600/Prawn+Fry.jpg", heading:"Eat nuts and seeds",extrecom:"Your vernacular won’t be limited without those words. “Great food is an experience and crystallizing that for the reader—the tastes, textures, and smells—is hallmark of great food writing,” says Ruth Evelyn Terry, a freelance writer. They are packed with protein, fiber, and a variety of vitamins and minerals",command:"Some people avoid nuts because they are high in fat. However, nuts and seeds are incredibly nutritious.  "},
      // {id:78, cat:"food", img:"https://tse1.mm.bing.net/th/id/OIP.dzAbvRfX50S9YBV2ajgjJAHaE8?pid=ImgDet&rs=1", heading:"Biryani ",extrecom:"The story behind the food is what makes for an interesting article. “Learn about what gives a plate more depth and your article will be more meaningful,” says Andrea Aliseda, a freelance writer. “The story behind the dish is what intrigues me. I like to find out what the circumstances are that brought the dish together. It’s an intrinsic part of what ends up on our plate,” she says. ",command:"Biryani is a mixed rice dish originating among the Muslims of South Asia."},
      {id:79,icon:"food", cat:"food", img:"https://awhealthcare.com/wp-content/uploads/2016/09/Healthy-Food.jpeg", heading:"Avoid bright lights before sleep ",extrecom:"“Food writing isn’t about food,” says Palmisano. “It’s about the people who make the food. Food is reflective of people’s traditions, their histories, and also the lands they come from. Food and identity are deeply connected, so a great story about food finds ways to weave context into the cuisine.  ",command:"When you’re exposed to bright lights — which contain blue light wavelengths — in the evening, it may disrupt your production of the sleep hormone melatonin"},
      {id:80,icon:"food", cat:"food", img:"https://tse2.mm.bing.net/th/id/OIP.4MR1qxYc69u7awyFmb_sGgHaGY?pid=ImgDet&rs=1", heading:"Avoid ultra-processed foods",extrecom:"Consider who was involved in making the meal and should be included in its story. “Food is under-politicized and under-contextualized. . . Highlight growers, talk about the history of food, and discuss how the food has been erased, colonized, or appropriated,” says Terry. ",command:"Ultra-processed foods (UPFs) are foods containing ingredients  contain additives like added sugar, highly  "},
      // {id:81,icon:"food", cat:"foodtop", img:"https://post.healthline.com/wp-content/uploads/2021/10/breakfast-foods-eggs-scrambled-pan-732x549-thumbnail.jpg",heading:"Get enough sleep",extrecom:"Readers are likely looking for information about the cuisine or seeking inspiration for places to eat. “Educate people about the restaurant, chef, or food that they’re eating. Inspire the audience to try a dish or ingredient,” says Jessica van Dop DeJesus of The Dining Traveler.  ",command:"What’s more, poor sleep is one of the strongest individual risk factors for weight gain and obesity. "},
      {id:82,icon:"food", cat:"foodtop",num:"2", img:"https://wallpapercave.com/wp/wp3724325.jpg",heading:" Eat adequate protein",extrecom:" A lack of background leads to unethical food writing. “Food tells a story. When the story is told irresponsibly, it doesn’t honor where it came from, who cooks it, who survives off of it, and whose memories and entangled in it,” says Alisea.",command:"Eating enough protein is vital for optimal health, as it provides the raw materials your body needs to create new cells and tissues"},
      {id:83,icon:"food", cat:"foodtop",num:"3", img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZBv-YKP4tJNWV4LWwThf4wsLwrtU__vkiYQ&usqp=CAU",heading:"Don’t fear coffee",extrecom:"Be aware that misrepresenting food could negatively impact the community who generously shared their cuisine with you. “Stereotypes can feed into how marginalized communities are treated in the food industry. Food media sets the bar with how the conversation about a culture’s cuisine is going to be discussed and has influence over public perception,” says Palmisano. ",command:"It’s rich in antioxidants, and some studies have linked coffee "},
      {id:84,icon:"food", cat:"foodtop",num:"4", img:"https://www.pixelstalk.net/wp-content/uploads/2016/08/Photography-Kebab-Meat-Food-Wallpaper-HD-Desktop-Computer.jpg" ,heading:" Eat fatty fish " ,extrecom:"Unethical writing about food can be a microaggression—intentionally or not. “Erasing and ignoring major foodways or treating them like exotic novelties, instead of equivalently sophisticated and created gastronomy, is racism,” says Terry. ",command:"Fish is a great source of high-quality protein and healthy fat. "},
      {id:85,icon:"food", cat:"new", img:"https://images.pexels.com/photos/16128579/pexels-photo-16128579/free-photo-of-landscape-of-a-river-and-mountains.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", heading:"Wind" ,extrecom:" Food appropriation is when people from outside a culture profit from food traditions. “The terms ‘upgraded’ and ‘elevated’ are used in menu descriptions for street food made by a white guy for white people,” says Ram. Avoid featuring white people who are benefitting from a cuisine that isn’t their own culture.",command:" There’s a whole world out there, right outside your window. You’d be a fool to miss it. —Charlotte Eriksson "},
      {id:86,icon:"food", cat:"food", img:"https://th.bing.com/th/id/R.62c1242f2b480bf5b34e630daced749b?rik=vtNwjhBrIh%2bbfg&riu=http%3a%2f%2fwww.howto-simplify.com%2fwp-content%2fuploads%2f2017%2f08%2f2018-06-04_0002.jpg&ehk=hpkAVViR0CICIJg1ma1HBXcbY7mJW%2bH0zLD4v2mxXR4%3d&risl=&pid=ImgRaw&r=0", heading:"Slow down",extrecom:"Seek expert commentary from community members. “When in doubt, get some feedback. For example, if I have to write about Vietnamese food, I reach out to a Vietnamese person who can help me with terminology and spelling,” says van Dop DeJesus. Use the real words for food rather than translating and anglicizing them. ",command:"The pace at which you eat influences how much you eat, as well as how likely you are to gain weight."},
      {id:87,icon:"food", cat:"food", img:"https://th.bing.com/th/id/R.25df87f8b1e255290d0652d1eb99ee57?rik=gE7TH5VSkNj3iQ&riu=http%3a%2f%2fblog.hdwallsource.com%2fwp-content%2fuploads%2f2015%2f01%2fitalian-food-wallpaper-hd-44478-45604-hd-wallpapers.jpg&ehk=0IwG2V7UvU20tfm02V2VdAAAV6OdjhX%2f3mGjBZXSPNk%3d&risl=&pid=ImgRaw&r=0", heading:"Don’t shop without a list",extrecom:" It’s especially crucial to use proper descriptors when writing about traditional, medicinal, or ceremonial foods. Research the proper terms to use that honor these dishes with deep cultural significance. Reach out to tourism boards, local chefs, or food historians. “Find restaurants, cookbooks, and grocery stores from the culture; visit them, walk around, and ask questions. Get to know the people, and ask them what terms they prefer,” says Ram.",command:"There are two important strategies to employ when you go grocery shopping: Make your shopping list ahead of time and don’t go to the store hungry. "},
    

    
 
      
      
      
      































      





         {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},
      {id:4, cat:"", img:"", heading:" " ,extrecom:" ",command:""},

      
      // {id:4, cat:"the latest", img:"https://images.pexels.com/photos/1796727/pexels-photo-1796727.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", heading:"THE LATEST IMAGES" },
      // {id:2, cat:"the latest", img:"https://images.pexels.com/photos/1796727/pexels-photo-1796727.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", heading:"THE LATEST IMAGES"},  
     

      // {id:1, cat:"latestarticles", img:"https://images.pexels.com/photos/3444648/pexels-photo-3444648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", heading:"The Latest articles by our Website", },
      // {id:1, cat:"latestarticles", img:"https://images.pexels.com/photos/3444648/pexels-photo-3444648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", heading:"The Latest articles by our Website", },
      // {id:1, cat:"latestarticles", img:"https://images.pexels.com/photos/3444648/pexels-photo-3444648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", heading:"The Latest articles by our Website", },

      
      
      

    ])
  return (
    <div>
      <store.Provider value={[data, setData]}>
        {props.children}
      </store.Provider>
    </div>
  )
}
export default ContextApi